#!/bin/sh -eu

# DO NOT EDIT THIS FILE!

# This file overwrites on every vml run. Set path to your program in
# `commands.clean.program` field of the main vml config if you want different
# behavior.

echo Running cleanup

clear_files() {
    for FILE in "$@"; do
        if [ -f "$FILE" ]; then
            :> "$FILE"
        fi
    done
}

clear_machine_id() {
    etc_machine_id=/etc/machine-id
    dbus_machine_id=/var/lib/dbus/machine-id

    [ -f "$etc_machine_id" ] || exit 0

    rm -f "$etc_machine_id" "$dbus_machine_id"
    touch "$etc_machine_id"
    chmod 0444 "$etc_machine_id"
}

remove_packages_cache() {
    apt-get clean ||:
    dnf clean all ||:
    rm -f /var/cache/apt/archives/*.rpm \
          /var/cache/apt/*.bin \
          /var/lib/apt/lists/*.* \
          #
}

clear_history() {
    rm -f .bash_history
}

clear_ssh() {
    clear_files .ssh/known_hosts .ssh/authorized_keys
}

cloud-init clean
clear_machine_id
clear_history
clear_ssh

rm "$0"

echo Cleaned successfully
